openapi: 3.0.3
info:
  title: Bookmarx API
  version: 1.0.0
  description: These are the OpenAPI specs that describe the REST API of Timecrack.
  termsOfService: github.com/alextselegidis/bookmarx
  contact:
    name: Bookmarx
    url: https://github.com/alextselegidis/bookmarx
    email: info@alextselegidis.com
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: http://localhost/api/v1
tags:
  - name: example
paths:
  /example:
    get:
      tags:
        - example
      summary: Example
      responses:
        '200':
          description: OK
